# dependabotの設定を無効化（コメントアウト）
# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 0
#     ignore:
#       - dependency-name: "*"
#
#   - package-ecosystem: "npm"
#     directory: "/apps/web"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 0
#     ignore:
#       - dependency-name: "*"
#
#   - package-ecosystem: "npm"
#     directory: "/apps/api"
#     schedule:
#       interval: "weekly"
#     open-pull-requests-limit: 0
#     ignore:
#       - dependency-name: "*"
